default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: wlk_user
  password: m?ufGwB9wlk

development:
  <<: *default
  database: wlk_distribution_development

test:
  <<: *default
  database: wlk_distribution_test

production:
  <<: *default
  database: wlk_distribution_production
  username: wlk_distribution
  password: <%= ENV["WLK_DISTRIBUTION_DATABASE_PASSWORD"] %>